name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 23

        - name: 🏗️ Install Dependencies
          run: npm install

        - name: 🧪 Test
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          run: npx wdio config/wdio.android.bs.conf.ts --spec test/specs/android/add-note-screen.spec.ts

        - name: 📦 Upload Logs
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs
